#!/bin/sh
# properties = {"type": "single", "rule": "Filter_loci", "local": false, "input": ["/beegfs/data/bguinet/these/NR_db", "/beegfs/data/bguinet/taxadb2/taxadb.sqlite", "/beegfs/data/soukkal/StageM2/Databases/Refseq_viral_db_nophages_nopolydna_IVSPER.faa"], "output": ["/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Candidate_viral_loci_Nr.m8", "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Candidate_viral_loci_Nr_taxid.m8", "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Candidate_viral_loci_filtered.m8", "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Fasta_viral_loci_filtered.fna", "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Fasta_viral_loci_filtered.faa"], "wildcards": {}, "params": {"threads": "10", "time": "24:00:00", "name": "Filter_loci", "out": "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Filter_loci.out", "err": "/beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Filter_loci.error"}, "log": [], "threads": 1, "resources": {}, "jobid": 162, "cluster": {}}
 cd /beegfs/data/soukkal/StageM2/Scripts/Homology_search && \
/beegfs/data/bguinet/Bguinet_conda/bin/python \
-m snakemake /beegfs/data/soukkal/StageM2/Control_genomes/results/Viral_Homology_results/Viral_loci/Candidate_viral_loci_Nr.m8 --snakefile /beegfs/data/soukkal/StageM2/Scripts/Homology_search/Snakemake_viral_homology_Control \
--force -j --keep-target-files --keep-remote --max-inventory-time 0 \
--wait-for-files /beegfs/data/soukkal/StageM2/Scripts/Homology_search/.snakemake/tmp.gy1vyf96 /beegfs/data/bguinet/these/NR_db /beegfs/data/bguinet/taxadb2/taxadb.sqlite /beegfs/data/soukkal/StageM2/Databases/Refseq_viral_db_nophages_nopolydna_IVSPER.faa --latency-wait 5 \
 --attempt 1 --force-use-threads --scheduler greedy \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules Filter_loci --nocolor --notemp --no-hooks --nolock --scheduler-solver-path /beegfs/data/bguinet/Bguinet_conda/bin \
--mode 2  && touch /beegfs/data/soukkal/StageM2/Scripts/Homology_search/.snakemake/tmp.gy1vyf96/162.jobfinished || (touch /beegfs/data/soukkal/StageM2/Scripts/Homology_search/.snakemake/tmp.gy1vyf96/162.jobfailed; exit 1)

